import 'dart:math';
import '../models/spot.dart';

/// 钓点服务（mock 版）
class SpotService {
  /// 城市列表（发现页 / 投稿页共用单一真源）
        static const List<String> cities = [
    '三亚',
    '上海',
    '上饶',
    '丽江',
    '乐山',
    '佛山',
    '凯里',
    '北京',
    '十堰',
    '南京',
    '南充',
    '南宁',
    '南昌',
    '厦门',
    '合肥',
    '哈尔滨',
    '大理',
    '大连',
    '天津',
    '宁波',
    '安康',
    '安顺',
    '宜宾',
    '常州',
    '常德',
    '广州',
    '库尔勒',
    '德宏',
    '德阳',
    '成都',
    '扬州',
    '无锡',
    '昆明',
    '昌吉',
    '普洱',
    '曲靖',
    '杭州',
    '松原',
    '柳州',
    '桂林',
    '楚雄',
    '武汉',
    '毕节',
    '汉中',
    '沈阳',
    '泉州',
    '济南',
    '海口',
    '深圳',
    '温州',
    '玉林',
    '玉溪',
    '百色',
    '眉山',
    '福州',
    '绵阳',
    '芜湖',
    '苏州',
    '西安',
    '贵阳',
    '赣州',
    '遵义',
    '郑州',
    '鄂州',
    '重庆',
    '长春',
    '长沙',
    '阜康',
    '青岛',
    '黄山',
    '黔东南',
    '黔西南',
  ];

  static final List<Spot> _mockSpots = [
    Spot(
    id: 's001', name: '六合龙池野钓点', type: '野钓', typeEmoji: '🐟',
    city: '南京', district: '六合', address: '六合区龙池大道尽头左手土路200米',
    latitude: 32.3521, longitude: 118.8501,
    images: ['https://picsum.photos/seed/s001a/800/500', 'https://picsum.photos/seed/s001b/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "鳊鱼"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '鳊鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费野钓，注意安全', businessHours: '全天开放',
    contactPhone: '13812345601',
    wechat: 'lh88801',
    ownerName: '老李',
    hasAccommodation: true,
    roomType: '湖边钓棚木屋',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '湖边钓棚木屋，含早约120元/人/晚，钓友拼住更划算，周末需提前订。',
    accommodationImages: const [
      'https://picsum.photos/seed/s001room1/400/300',
      'https://picsum.photos/seed/s001room2/400/300',
    ],
    commonAreaImages: const [
      'https://picsum.photos/seed/s001area1/400/300',
      'https://picsum.photos/seed/s001area2/400/300',
    ],
    facilities: const ['停车场', '餐厅', '淋浴热水', '渔具出租', 'WiFi'],
    rating: 4.6, reviewCount: 89, viewCount: 3200, favoriteCount: 412, postCount: 23,
    description: '水质清澈，鲫鱼密度高，适合手竿。近岸有缓坡，停车方便。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's002', name: '石臼湖冬钓基地', type: '游钓基地', typeEmoji: '🏄',
    city: '南京', district: '溧水', address: '溧水区石臼湖南岸',
    latitude: 31.415, longitude: 119.018,
    images: ['https://picsum.photos/seed/s002a/800/500'],
    fishSpecies: ["草鱼", "青鱼", "鳜鱼", "翘嘴"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-07',
    stockingCycleDays: 30,
    price: 80, priceNote: '按天收费，竿费另算', businessHours: '06:00-18:00',
    contactPhone: '13812345602',
    wechat: 'fyj88802',
    ownerName: '张老板',
    rating: 4.8, reviewCount: 156, viewCount: 5600, favoriteCount: 723, postCount: 45,
    description: '国家二级水源保护地，鱼种丰富。冬季草洞密度极高，有配套餐饮。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's003', name: '金牛湖深水钓区', type: '斤塘', typeEmoji: '🎣',
    city: '南京', district: '六合', address: '六合区金牛湖水库',
    latitude: 32.388, longitude: 118.88,
    images: ['https://picsum.photos/seed/s003a/800/500'],
    fishSpecies: ["青鱼", "草鱼", "鲤鱼", "鳙鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-06',
    stockingCycleDays: 7,
    price: 120, priceNote: '包天￥120，渔获按斤回收', businessHours: '06:00-17:00',
    contactPhone: '13812345603',
    wechat: 'jnh88803',
    ownerName: '周老板',
    rating: 4.7, reviewCount: 203, viewCount: 7800, favoriteCount: 891, postCount: 67,
    description: '水库规模大，青鱼十几斤常见。深水区有标点，岸钓台钓皆可。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's004', name: '固城湖枯水钓位', type: '野钓', typeEmoji: '🐟',
    city: '南京', district: '高淳', address: '高淳区固城湖东岸',
    latitude: 31.328, longitude: 118.882,
    images: ['https://picsum.photos/seed/s004a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鳊鱼", "黄颡鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鳊鱼': '4-10', '黄颡鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，停车￥10/天', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 67, viewCount: 2100, favoriteCount: 234, postCount: 18,
    description: '枯水期结构全露，是找鱼的好时机。黄颡鱼晚上活性高。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's005', name: '滁河浦口段', type: '野钓', typeEmoji: '🐟',
    city: '南京', district: '浦口', address: '浦口区三合圩泵站附近',
    latitude: 32.128, longitude: 118.62,
    images: ['https://picsum.photos/seed/s005a/800/500'],
    fishSpecies: ["鲫鱼", "黄颡鱼", "鳜鱼", "翘嘴"],
    fishPeakSeason: const { '鲫鱼': '3-11', '黄颡鱼': '4-10', '鳜鱼': '5-10', '翘嘴': '6-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 112, viewCount: 4100, favoriteCount: 456, postCount: 31,
    description: '河面宽水流缓，凌晨四点是黄金窗口。闸口下游是好标点。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's006', name: '千岛湖鳜鱼深处', type: '游钓基地', typeEmoji: '🏄',
    city: '杭州', district: '淳安', address: '淳安县千岛湖西南湖区',
    latitude: 29.608, longitude: 118.88,
    images: ['https://picsum.photos/seed/s006a/800/500'],
    fishSpecies: ["鳜鱼", "鲈鱼", "鳙鱼", "青鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-03',
    stockingCycleDays: 30,
    price: 200, priceNote: '按天￥200，含船费，渔获另计价', businessHours: '06:00-17:00，需预约',
    contactPhone: '13812345606',
    wechat: 'qdh06',
    ownerName: '千岛湖王',
    rating: 4.9, reviewCount: 287, viewCount: 12000, favoriteCount: 1456, postCount: 98,
    description: '国内顶级路亚目的地，水深12米鳜鱼密度极高。米级鳜鱼常有。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '湖景木屋/度假村标间',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '千岛湖度假村配套，木屋别墅+湖景标间，WiFi覆盖，含早餐，需提前预约。',
    accommodationImages: const [
      'https://picsum.photos/seed/s006room1/400/300',
      'https://picsum.photos/seed/s006room2/400/300',
    ],
    commonAreaImages: const [
      'https://picsum.photos/seed/s006area1/400/300',
      'https://picsum.photos/seed/s006area2/400/300',
    ],
    facilities: const ['WiFi', '停车场', '餐厅', '温泉', '水上娱乐'],
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's007', name: '西溪湿地夜钓点', type: '农家乐', typeEmoji: '🏕',
    city: '杭州', district: '西湖', address: '西湖区西溪湿地公园东门',
    latitude: 30.275, longitude: 120.062,
    images: ['https://picsum.photos/seed/s007a/800/500'],
    fishSpecies: ["螺蛳青", "草鱼", "鲤鱼", "鳊鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-02',
    stockingCycleDays: 30,
    price: 150, priceNote: '含钓位+简餐，渔获回收', businessHours: '18:00-02:00',
    contactPhone: '13812345607',
    wechat: 'xxf07',
    ownerName: '西溪渔翁',
    rating: 4.7, reviewCount: 134, viewCount: 6200, favoriteCount: 678, postCount: 42,
    description: '夜捞螺蛳青是招牌，十斤以上常见。环境好，有农家菜配套。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '农家乐客房',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '农家乐住宿，标间/大床均有，含早餐。需提前预约。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's008', name: '象山港潮汐钓点', type: '野钓', typeEmoji: '🐟',
    city: '宁波', district: '象山', address: '象山县象山港拦河闸下游',
    latitude: 29.462, longitude: 121.835,
    images: ['https://picsum.photos/seed/s008a/800/500'],
    fishSpecies: ["青蟹", "鲈鱼", "黄鳍鲷", "海鳗"],
    fishPeakSeason: const { '青蟹': '4-11', '鲈鱼': '5-10', '黄鳍鲷': '1-12', '海鳗': '5-11' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，注意潮汐', businessHours: '看潮汐，大潮活汛最佳',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 98, viewCount: 4300, favoriteCount: 389, postCount: 27,
    description: '小潮活汛出鱼最好，青蟹用鸡肝打窝，黄鳍鲷用路亚抽停。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's009', name: '梅山岛重障碍路亚', type: '野钓', typeEmoji: '🐟',
    city: '宁波', district: '北仑', address: '北仑区梅山岛东南海岸',
    latitude: 29.812, longitude: 122.092,
    images: ['https://picsum.photos/seed/s009a/800/500'],
    fishSpecies: ["海鲈", "黄鳍鲷", "黑鲷", "真鲷"],
    fishPeakSeason: const { '海鲈': '9-3', '黄鳍鲷': '1-12', '黑鲷': '10-3', '真鲷': '10-4' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，需自带路亚装备', businessHours: '潮汐窗口期',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 76, viewCount: 3800, favoriteCount: 345, postCount: 22,
    description: '重障碍区强抽，一斤半海鲈常见。安全装备必备。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's010', name: '楠溪江浅滩鳜鱼', type: '野钓', typeEmoji: '🐟',
    city: '温州', district: '永嘉', address: '永嘉县楠溪江岩头镇段',
    latitude: 28.182, longitude: 120.692,
    images: ['https://picsum.photos/seed/s010a/800/500'],
    fishSpecies: ["鳜鱼", "光唇鱼", "马口鱼", "溪石斑"],
    fishPeakSeason: const { '鳜鱼': '5-10', '光唇鱼': '4-10', '马口鱼': '4-10', '溪石斑': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费生态保护区', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.8, reviewCount: 145, viewCount: 5600, favoriteCount: 612, postCount: 38,
    description: '水质国家一级，好标点在浅滩石头后面。早上五点到七点是窗口期。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's011', name: '洞头岛船路亚', type: '游钓基地', typeEmoji: '🏄',
    city: '温州', district: '洞头', address: '洞头区东屏街道渔港码头',
    latitude: 27.835, longitude: 121.168,
    images: ['https://picsum.photos/seed/s011a/800/500'],
    fishSpecies: ["黄鳍鲷", "黑鲷", "海鲈", "GT（牛港鲹）"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-29',
    stockingCycleDays: 30,
    price: 300, priceNote: '包船出海￥300，含铅头钩+T尾饵料', businessHours: '07:00-16:00，需提前预约',
    contactPhone: '13812345611',
    wechat: 'dt11',
    ownerName: '洞头阿海',
    rating: 4.9, reviewCount: 89, viewCount: 7200, favoriteCount: 834, postCount: 51,
    description: '船路亚，黄鳍鲷连竿，GT抽到手软。有船长熟悉标点。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's012', name: '都江堰马口溪流', type: '野钓', typeEmoji: '🐟',
    city: '成都', district: '都江堰', address: '都江堰市龙池镇山涧溪流',
    latitude: 31.002, longitude: 103.602,
    images: ['https://picsum.photos/seed/s012a/800/500'],
    fishSpecies: ["马口鱼", "山女鳟", "原生虹鳟", "溪哥"],
    fishPeakSeason: const { '马口鱼': '4-10', '山女鳟': '4-10', '原生虹鳟': '4-10', '溪哥': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，小雨天龙其活跃', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.7, reviewCount: 178, viewCount: 6800, favoriteCount: 756, postCount: 44,
    description: '小雨天龙活性极高，瓜子亮片三小时连竿。高原溪流风景极好。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's013', name: '大渡河野钓营地', type: '野钓', typeEmoji: '🐟',
    city: '乐山', district: '沙湾', address: '乐山市沙湾区大渡河畔',
    latitude: 29.342, longitude: 103.548,
    images: ['https://picsum.photos/seed/s013a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鲶鱼", "黄辣丁"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鲶鱼': '5-9', '黄辣丁': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，营地停车￥20', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 87, viewCount: 3200, favoriteCount: 298, postCount: 21,
    description: '大回湾处鱼密度高，打完窝子半小时开始连竿。鲶鱼夜间凶猛。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's014', name: '金沙江江团基地', type: '斤塘', typeEmoji: '🎣',
    city: '宜宾', district: '翠屏', address: '宜宾市金沙江下游三江湖段',
    latitude: 28.752, longitude: 104.63,
    images: ['https://picsum.photos/seed/s014a/800/500'],
    fishSpecies: ["江团", "黄辣丁", "鲤鱼", "草鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-26',
    stockingCycleDays: 7,
    price: 80, priceNote: '￥80/天，鸡肝打窝', businessHours: '全天开放',
    contactPhone: '13812345614',
    wechat: 'ybin14',
    ownerName: '宜宾老张',
    rating: 4.6, reviewCount: 134, viewCount: 4800, favoriteCount: 523, postCount: 36,
    description: '鸡肝打窝江团疯狂开口，三小时十几条。黄辣丁两指宽很常见。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's015', name: '红枫湖大口黑鲈', type: '游钓基地', typeEmoji: '🏄',
    city: '贵阳', district: '清镇', address: '清镇市红枫湖国家湿地公园',
    latitude: 26.582, longitude: 106.438,
    images: ['https://picsum.photos/seed/s015a/800/500'],
    fishSpecies: ["大口黑鲈", "鳜鱼", "鳙鱼", "翘嘴"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-25',
    stockingCycleDays: 30,
    price: 150, priceNote: '包船￥150，含装备', businessHours: '07:00-17:00',
    contactPhone: '13812345615',
    wechat: 'gf15',
    ownerName: '贵阳路亚侠',
    rating: 4.8, reviewCount: 198, viewCount: 8900, favoriteCount: 987, postCount: 62,
    description: '夏天窗口期6-9点，船长30cm的大口黑鲈常见。湖路亚必去。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's016', name: '乌江渡野钓', type: '野钓', typeEmoji: '🐟',
    city: '遵义', district: '播州', address: '遵义市播州区乌江渡水电站下游',
    latitude: 27.452, longitude: 106.842,
    images: ['https://picsum.photos/seed/s016a/800/500'],
    fishSpecies: ["草鱼", "鲤鱼", "青鱼", "黄颡鱼"],
    fishPeakSeason: const { '草鱼': '4-10', '鲤鱼': '4-11', '青鱼': '5-10', '黄颡鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，水质好', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 76, viewCount: 2900, favoriteCount: 312, postCount: 19,
    description: '乌江水质国家二级，草鱼个体大，打完窝子等半小时来口。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's017', name: '滇池野钓湾', type: '野钓', typeEmoji: '🐟',
    city: '昆明', district: '西山区', address: '西山区滇池西岸海口镇',
    latitude: 24.952, longitude: 102.648,
    images: ['https://picsum.photos/seed/s017a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "罗非", "金线鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '罗非': '5-10', '金线鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费生态保护区域', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 156, viewCount: 5100, favoriteCount: 534, postCount: 33,
    description: '早上五点半到九点上六条鲤鱼，最大六斤。秋季是旺季。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's018', name: '阳宗海路亚基地', type: '游钓基地', typeEmoji: '🏄',
    city: '昆明', district: '宜良', address: '昆明市宜良县阳宗海湖畔',
    latitude: 24.982, longitude: 102.998,
    images: ['https://picsum.photos/seed/s018a/800/500'],
    fishSpecies: ["大口黑鲈", "鳜鱼", "翘嘴", "罗非"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-22',
    stockingCycleDays: 30,
    price: 120, priceNote: '￥120/天，含船', businessHours: '07:00-17:00',
    contactPhone: '13812345618',
    wechat: 'yzh18',
    ownerName: '云南路亚',
    rating: 4.7, reviewCount: 112, viewCount: 6700, favoriteCount: 698, postCount: 41,
    description: '鲈鱼密度高，新手下沉系路亚上鱼很快。景色绝美。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '华侨城度假区酒店/木屋',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '华侨城滨水湿地公园内配套酒店+木屋别墅，餐厅/温泉/水上娱乐齐全。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's019', name: '洱海手竿钓场', type: '农家乐', typeEmoji: '🏕',
    city: '大理', district: '下关', address: '大理市洱海西岸才村码头',
    latitude: 25.692, longitude: 100.182,
    images: ['https://picsum.photos/seed/s019a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "弓鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-21',
    stockingCycleDays: 30,
    price: 100, priceNote: '￥100含钓位+农家菜', businessHours: '06:00-18:00',
    contactPhone: '13812345619',
    wechat: 'dl19',
    ownerName: '大理阿鹏',
    rating: 4.8, reviewCount: 234, viewCount: 9100, favoriteCount: 1023, postCount: 58,
    description: '洱海西岸浅滩秋季鲫鱼肥，酒米打窝连竿。风景绝美，配套餐饮。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '洱海民宿标间',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '洱海边民宿，标间/大床，WiFi覆盖。旺季需提前订房。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's020', name: '太平湖深水鳜鱼', type: '游钓基地', typeEmoji: '🏄',
    city: '黄山', district: '黄山区', address: '黄山市黄山区太平湖镇',
    latitude: 30.298, longitude: 118.128,
    images: ['https://picsum.photos/seed/s020a/800/500'],
    fishSpecies: ["鳜鱼", "鲈鱼", "鳙鱼", "青鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-09',
    stockingCycleDays: 30,
    price: 180, priceNote: '包船￥180，含路亚装备', businessHours: '07:00-17:00，需预约',
    contactPhone: '13812345620',
    wechat: 'tph20',
    ownerName: '漓水渔夫',
    rating: 4.9, reviewCount: 167, viewCount: 8200, favoriteCount: 934, postCount: 55,
    description: '米级鳜鱼常见，下午三点窗口期，一口切线两次才拿下。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's021', name: '锦城湖晨练场', type: '野钓', typeEmoji: '🐟',
    city: '成都', district: '高新区', address: '成都高新区锦城湖公园',
    latitude: 30.562, longitude: 104.062,
    images: ['https://picsum.photos/seed/s021a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "罗非"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '罗非': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '公园免费，停车￥5/小时', businessHours: '公园开放时间06:00-22:00',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 89, viewCount: 2300, favoriteCount: 187, postCount: 12,
    description: '市区内最近的选择，早晚鱼口可以。放水日无口。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's022', name: '拉市海高原钓点', type: '野钓', typeEmoji: '🐟',
    city: '大理', district: '玉龙', address: '丽江市玉龙县拉市海高原湿地',
    latitude: 26.902, longitude: 100.102,
    images: ['https://picsum.photos/seed/s022a/800/500'],
    fishSpecies: ["高原鳅", "金线鱼", "草鱼"],
    fishPeakSeason: const { '高原鳅': '5-9', '金线鱼': '4-10', '草鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 50, priceNote: '湿地保护费￥50，含船只', businessHours: '08:00-17:00',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 67, viewCount: 3100, favoriteCount: 267, postCount: 16,
    description: '高原湿地鱼种特殊，路亚瓜子饵效果好。风景绝美。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's023', name: '星路亚·华侨城基地', type: '路亚', typeEmoji: '🎮',
    city: '昆明', district: '宜良', address: '昆明市宜良县阳宗海华侨城滨水湿地公园',
    latitude: 24.921, longitude: 102.483,
    images: ['https://picsum.photos/seed/s023a/800/500', 'https://picsum.photos/seed/s023b/800/500'],
    fishSpecies: ["大口黑鲈", "鳜鱼", "翘嘴", "黑鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-06',
    stockingCycleDays: 30,
    price: 150, priceNote: '￥150/天，含装备', businessHours: '07:00-18:00',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 78, viewCount: 4100, favoriteCount: 321, postCount: 18,
    description: '阳宗海边100亩路亚基地，云南最美路亚钓场。华侨城滨水湿地公园配套完善，餐厅/温泉/水上娱乐一应俱全，家人同游首选。鲈鱼密度高，入门友好。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's024', name: '安宁玉龙湾国际路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '昆明', district: '安宁', address: '昆明市安宁市太平镇玉龙湾（导航玉龙湾高尔夫球会停车场）',
    latitude: 24.932, longitude: 102.483,
    images: ['https://picsum.photos/seed/s024a/800/500', 'https://picsum.photos/seed/s024b/800/500'],
    fishSpecies: ["大口黑鲈", "鳜鱼", "翘嘴", "彩虹鳟", "金鳟"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-05',
    stockingCycleDays: 30,
    price: 280, priceNote: '￥280/天，含装备+午餐', businessHours: '08:00-17:00，需预约',
    contactPhone: '0871-68630526',
    wechat: null,
    ownerName: '云南远大·玉龙湾国际路亚基地',
    rating: 4.7, reviewCount: 412, viewCount: 22000, favoriteCount: 3200, postCount: 186,
    description: '安宁太平镇玉龙湾，500亩水面，两面环山，结构丰富。配备20条专业路亚艇、救援艇、300㎡俱乐部会所。目标鱼：鲈鱼/军鱼/丁桂/黑鱼。配套停车场、餐饮、高尔夫球会。定位高端，承办各类路亚赛事。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's025', name: '柴石滩水库', type: '野钓', typeEmoji: '🐟',
    city: '昆明', district: '宜良', address: '昆明市宜良县狗街镇柴石滩水库',
    latitude: 24.871, longitude: 103.148,
    images: ['https://picsum.photos/seed/s025a/800/500', 'https://picsum.photos/seed/s025b/800/500'],
    fishSpecies: ["青鱼", "草鱼", "鲤鱼", "鳜鱼", "鲢鳙"],
    fishPeakSeason: const { '青鱼': '5-10', '草鱼': '4-10', '鲤鱼': '4-11', '鳜鱼': '5-10', '鲢鳙': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费野钓，自备装备', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    hasAccommodation: true,
    roomType: '景区农家乐客房',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '柴石滩水库景区内有农家乐可住宿，标间/多人间。旺季及节假日需提前订房。',
    rating: 4.4, reviewCount: 312, viewCount: 15800, favoriteCount: 2104, postCount: 127,
    description: '宜良柴石滩，昆明钓友最爱的大物塘。青鱼二三十斤常见，水面大需船或长竿守底。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's026', name: '云鹏水库', type: '野钓', typeEmoji: '🐟',
    city: '昆明', district: '宜良', address: '昆明市宜良县竹山镇云鹏水库',
    latitude: 24.751, longitude: 103.281,
    images: ['https://picsum.photos/seed/s026a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "罗非", "黄鳝"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '罗非': '5-10', '黄鳝': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费野钓，禁止船钓', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 89, viewCount: 4300, favoriteCount: 445, postCount: 31,
    description: '宜良竹山镇，水质好，罗非大个体。岸边有缓坡可搭帐篷过夜，是昆明钓友口碑不错的野钓点。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '帐篷位（自带帐篷）',
    roomCapacity: null,
    hasWifi: false,
    accommodationNote: '岸边缓坡可搭帐篷过夜，无配套设施，请自备露营装备及补给。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's027', name: '南盘江罗非天堂', type: '野钓', typeEmoji: '🐟',
    city: '曲靖', district: '麒麟', address: '曲靖市麒麟区南盘江三宝镇段',
    latitude: 25.492, longitude: 103.798,
    images: ['https://picsum.photos/seed/s027a/800/500'],
    fishSpecies: ["罗非", "鲢鱼", "鳙鱼", "黑鱼"],
    fishPeakSeason: const { '罗非': '5-10', '鲢鱼': '5-9', '鳙鱼': '5-9', '黑鱼': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 98, viewCount: 3400, favoriteCount: 312, postCount: 23,
    description: '夏天南盘江罗非密度高手竿拉到手酸，注意防暑。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's028', name: '新安江拦河堰', type: '野钓', typeEmoji: '🐟',
    city: '黄山', district: '屯溪', address: '黄山市屯溪区新安江拦河堰下游',
    latitude: 29.715, longitude: 118.338,
    images: ['https://picsum.photos/seed/s028a/800/500'],
    fishSpecies: ["马口鱼", "光唇鱼", "溪石斑", "鳜鱼"],
    fishPeakSeason: const { '马口鱼': '4-10', '光唇鱼': '4-10', '溪石斑': '4-10', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，出差路过必刷', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 123, viewCount: 4700, favoriteCount: 489, postCount: 29,
    description: '拦河堰下游闸口，半小时三条马口。出差路过不可错过。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's029', name: '瓦屋山原生鳟鱼', type: '野钓', typeEmoji: '🐟',
    city: '眉山', district: '洪雅', address: '眉山市洪雅县瓦屋山溪流',
    latitude: 29.682, longitude: 103.012,
    images: ['https://picsum.photos/seed/s029a/800/500'],
    fishSpecies: ["原生虹鳟", "山女鳟", "马口鱼", "溪哥"],
    fishPeakSeason: const { '原生虹鳟': '4-10', '山女鳟': '4-10', '马口鱼': '4-10', '溪哥': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费生态保护区', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.9, reviewCount: 145, viewCount: 7800, favoriteCount: 845, postCount: 47,
    description: '高山水库出来的水，鳟鱼活性极好，飞蝇钩中鱼体验极佳。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '山中客栈标间',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '瓦屋山农家客栈，标间/多人间，高山环境无WiFi。需提前订房。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's030', name: '溧水农家乐斤塘', type: '农家乐', typeEmoji: '🏕',
    city: '南京', district: '溧水', address: '溧水区东屏镇渔乐山庄',
    latitude: 31.352, longitude: 119.052,
    images: ['https://picsum.photos/seed/s030a/800/500'],
    fishSpecies: ["草鱼", "青鱼", "鲤鱼", "花鲢"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-30',
    stockingCycleDays: 30,
    price: 100, priceNote: '￥100/人，含餐饮，渔获回收价￥3/斤', businessHours: '07:00-18:00',
    contactPhone: '13812345626',
    wechat: 'ylsz26',
    ownerName: '王老板',
    rating: 4.5, reviewCount: 189, viewCount: 5200, favoriteCount: 467, postCount: 28,
    description: '农家乐配套完善，适合家庭聚会。渔获回收有保障。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '农家乐标间',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '农家乐住宿含早，适合家庭周末出行，提前预约。',
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's031', name: '温州龙湾养殖塘', type: '养殖塘', typeEmoji: '🐠',
    city: '温州', district: '龙湾', address: '温州市龙湾区永中街道水产养殖基地',
    latitude: 27.928, longitude: 120.852,
    images: ['https://picsum.photos/seed/s031a/800/500'],
    fishSpecies: ["草鱼", "青鱼", "鳙鱼", "加州鲈"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-29',
    stockingCycleDays: 30,
    price: 60, priceNote: '￥60/竿，渔获称重计价', businessHours: '06:00-18:00',
    contactPhone: '13812345627',
    wechat: 'wz27',
    ownerName: '温州老郑',
    rating: 4.3, reviewCount: 87, viewCount: 2800, favoriteCount: 234, postCount: 15,
    description: '养殖塘密度高，适合新手练手。老板人好，会教调漂。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's032', name: '黔东南都柳江野钓', type: '野钓', typeEmoji: '🐟',
    city: '黔东南', district: '从江', address: '黔东南从江县都柳江丙妹镇段',
    latitude: 25.752, longitude: 108.902,
    images: ['https://picsum.photos/seed/s032a/800/500'],
    fishSpecies: ["军鱼", "光唇鱼", "鳜鱼", "马口鱼"],
    fishPeakSeason: const { '军鱼': '5-10', '光唇鱼': '4-10', '鳜鱼': '5-10', '马口鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.7, reviewCount: 56, viewCount: 2900, favoriteCount: 345, postCount: 18,
    description: '标点在大石头后面，路亚瓜子饵中斤级军鱼，贵州必刷。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's033', name: '安顺黄果树河段', type: '野钓', typeEmoji: '🐟',
    city: '安顺', district: '镇宁', address: '安顺市镇宁县黄果树景区下游',
    latitude: 25.992, longitude: 105.618,
    images: ['https://picsum.photos/seed/s033a/800/500'],
    fishSpecies: ["溪石斑", "马口鱼", "光唇鱼", "黄辣丁"],
    fishPeakSeason: const { '溪石斑': '4-10', '马口鱼': '4-10', '光唇鱼': '4-10', '黄辣丁': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费生态保护', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 78, viewCount: 3400, favoriteCount: 378, postCount: 21,
    description: '游客都在看瀑布，我在旁边钓鱼。游客走了鱼才开始开口。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's034', name: '泸州长江野钓', type: '野钓', typeEmoji: '🐟',
    city: '泸州', district: '江阳', address: '泸州市江阳区长江滨江路',
    latitude: 28.872, longitude: 105.442,
    images: ['https://picsum.photos/seed/s034a/800/500'],
    fishSpecies: ["草鱼", "鲤鱼", "鲢鱼", "江团"],
    fishPeakSeason: const { '草鱼': '4-10', '鲤鱼': '4-11', '鲢鱼': '5-9', '江团': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 65, viewCount: 2100, favoriteCount: 189, postCount: 11,
    description: '长江边上一个人坐了一下午，就上一条草鱼，但风景值了。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's035', name: '楚雄青山湖水库', type: '养殖塘', typeEmoji: '🐠',
    city: '楚雄', district: '楚雄市', address: '东瓜镇青山湖水库(导航云南俏江福农庄)',
    latitude: 25.05, longitude: 101.55,
    images: ['https://picsum.photos/seed/s035a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "青鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-25',
    stockingCycleDays: 30,
    price: 60, priceNote: '￥60/天', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 45, viewCount: 1200, favoriteCount: 156, postCount: 9,
    description: '楚雄近郊养殖塘，停车方便，适合周末家庭出钓。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's036', name: '德宏那目水库', type: '野钓', typeEmoji: '🐟',
    city: '德宏', district: '芒市', address: '德宏州芒市那目水库',
    latitude: 24.43, longitude: 98.58,
    images: ['https://picsum.photos/seed/s036a/800/500'],
    fishSpecies: ["鲢鱼", "鳙鱼", "鲤鱼", "草鱼"],
    fishPeakSeason: const { '鲢鱼': '5-9', '鳙鱼': '5-9', '鲤鱼': '4-11', '草鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.1, reviewCount: 38, viewCount: 980, favoriteCount: 123, postCount: 7,
    description: '芒市近郊水库，水质好，鲢鳙个体大，适合手竿守底。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's037', name: '贵阳百花湖', type: '野钓', typeEmoji: '🐟',
    city: '贵阳', district: '观山湖区', address: '贵阳市观山湖区百花湖乡',
    latitude: 26.62, longitude: 106.52,
    images: ['https://picsum.photos/seed/s037a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鲢鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鲢鱼': '5-9', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 67, viewCount: 2100, favoriteCount: 234, postCount: 14,
    description: '贵阳近郊水库，鱼种丰富，周末常有人出钓。风景好。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's038', name: '兴义万峰湖', type: '野钓', typeEmoji: '🐟',
    city: '黔西南', district: '兴义', address: '黔西南兴义市万峰湖',
    latitude: 25.08, longitude: 104.88,
    images: ['https://picsum.photos/seed/s038a/800/500'],
    fishSpecies: ["罗非", "鲤鱼", "草鱼", "青鱼"],
    fishPeakSeason: const { '罗非': '5-10', '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，库区野钓注意安全', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 112, viewCount: 3400, favoriteCount: 456, postCount: 22,
    description: '万峰湖渔业养殖场（企业名公开），鱼种多密度高，贵州路亚热门地。商家可后续认领。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's039', name: '毕节东风湖', type: '野钓', typeEmoji: '🐟',
    city: '毕节', district: '黔西', address: '毕节市黔西市东风湖（乌江上游渡口）',
    latitude: 27.0, longitude: 105.83,
    images: ['https://picsum.photos/seed/s039a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鲢鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鲢鱼': '5-9', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 52, viewCount: 1800, favoriteCount: 198, postCount: 10,
    description: '东风湖乌江上游段，水面大鱼种多，路亚台钓皆可。商家可后续认领。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's040', name: '桂林青狮潭水库', type: '野钓', typeEmoji: '🐟',
    city: '桂林', district: '灵川', address: '桂林市灵川县青狮潭水库',
    latitude: 25.48, longitude: 110.28,
    images: ['https://picsum.photos/seed/s040a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 78, viewCount: 2300, favoriteCount: 312, postCount: 15,
    description: '桂林经典野钓点，水库规模大，青鱼十几斤常见。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's041', name: '桂林漓江', type: '野钓', typeEmoji: '🐟',
    city: '桂林', district: '灵川', address: '桂林市灵川县大圩镇漓江段',
    latitude: 25.52, longitude: 110.35,
    images: ['https://picsum.photos/seed/s041a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鳜鱼", "黄颡鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鳜鱼': '5-10', '黄颡鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，注意漓江汛期', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 134, viewCount: 4200, favoriteCount: 567, postCount: 28,
    description: '漓江大圩段，鳜鱼密度高，路亚瓜子饵中鱼率高。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's042', name: '百色澄碧河水库', type: '野钓', typeEmoji: '🐟',
    city: '百色', district: '右江', address: '百色市右江区澄碧河水库',
    latitude: 23.9, longitude: 106.6,
    images: ['https://picsum.photos/seed/s042a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "罗非"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '罗非': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 45, viewCount: 1400, favoriteCount: 189, postCount: 9,
    description: '百色近郊水库，鲤鱼草鱼密度高，适合休闲野钓。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's043', name: '南宁大王滩水库', type: '野钓', typeEmoji: '🐟',
    city: '南宁', district: '良庆', address: '南宁市良庆区大王滩水库',
    latitude: 22.72, longitude: 108.52,
    images: ['https://picsum.photos/seed/s043a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鲢鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鲢鱼': '5-9', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 67, viewCount: 1900, favoriteCount: 245, postCount: 12,
    description: '南宁近郊水库，钓点成熟，周末人气高。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's044', name: '柳州柳江', type: '野钓', typeEmoji: '🐟',
    city: '柳州', district: '柳南', address: '柳州市柳南区柳江沿岸',
    latitude: 24.32, longitude: 109.42,
    images: ['https://picsum.photos/seed/s044a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "黄颡鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '黄颡鱼': '4-10', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 98, viewCount: 2800, favoriteCount: 378, postCount: 18,
    description: '柳江市区段，鳜鱼黄颡鱼密度高，夜钓效果好。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's045', name: '阳朔遇龙河', type: '野钓', typeEmoji: '🐟',
    city: '桂林', district: '阳朔', address: '桂林市阳朔县遇龙河白沙镇段',
    latitude: 24.92, longitude: 110.45,
    images: ['https://picsum.photos/seed/s045a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "鳜鱼", "黄颡鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '鳜鱼': '5-10', '黄颡鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费生态保护区', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.7, reviewCount: 145, viewCount: 4900, favoriteCount: 623, postCount: 31,
    description: '遇龙河水质清澈，鳜鱼黄颡鱼密度高，划竹筏打窝效果极佳。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's046', name: '玉林苏烟水库', type: '野钓', typeEmoji: '🐟',
    city: '玉林', district: '玉州', address: '玉林市玉州区苏烟水库',
    latitude: 22.63, longitude: 110.17,
    images: ['https://picsum.photos/seed/s046a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "罗非"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '罗非': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.1, reviewCount: 38, viewCount: 1100, favoriteCount: 145, postCount: 7,
    description: '玉林近郊水库，适合休闲野钓。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's047', name: '南部升钟湖', type: '黑坑', typeEmoji: '🏴‍☠️',
    city: '南充', district: '南部', address: '南充市南部县升钟湖',
    latitude: 31.35, longitude: 105.82,
    images: ['https://picsum.photos/seed/s047a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鳜鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-02',
    stockingCycleDays: 7,
    price: 0, priceNote: '免费，库区野钓注意安全', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 156, viewCount: 5600, favoriteCount: 734, postCount: 38,
    description: '西南最大人工湖之一，鱼种齐全，青鱼二三十斤常见，钓鱼人朝圣地。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's048', name: '仁寿黑龙滩', type: '黑坑', typeEmoji: '🏴‍☠️',
    city: '眉山', district: '仁寿', address: '眉山市仁寿县黑龙滩水库',
    latitude: 30.08, longitude: 104.12,
    images: ['https://picsum.photos/seed/s048a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鳜鱼", "翘嘴"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-01',
    stockingCycleDays: 7,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 112, viewCount: 3800, favoriteCount: 489, postCount: 26,
    description: '仁寿黑龙滩，成都钓友最爱的大物塘。水面大，青鱼常见。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's049', name: '简阳三岔湖', type: '野钓', typeEmoji: '🐟',
    city: '成都', district: '简阳', address: '成都市简阳市三岔湖',
    latitude: 30.42, longitude: 104.28,
    images: ['https://picsum.photos/seed/s049a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鳜鱼", "翘嘴"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '鳜鱼': '5-10', '翘嘴': '6-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费，水库注意安全', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.7, reviewCount: 198, viewCount: 7200, favoriteCount: 892, postCount: 52,
    description: '成都最大人工湖，鳜鱼翘嘴密度高，路亚台钓两相宜。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's050', name: '三台鲁班水库', type: '野钓', typeEmoji: '🐟',
    city: '绵阳', district: '三台', address: '绵阳市三台县鲁班水库',
    latitude: 30.78, longitude: 105.05,
    images: ['https://picsum.photos/seed/s050a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "黄颡鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '黄颡鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 67, viewCount: 2100, favoriteCount: 278, postCount: 14,
    description: '鲁班水库鱼种丰富，青鱼个体大，适合守底博大物。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's051', name: '中江继光水库', type: '野钓', typeEmoji: '🐟',
    city: '德阳', district: '中江', address: '德阳市中江县继光水库',
    latitude: 31.12, longitude: 104.78,
    images: ['https://picsum.photos/seed/s051a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 89, viewCount: 2900, favoriteCount: 345, postCount: 19,
    description: '继光水库水质好，草鱼青鱼密度高，成都钓友常去。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's052', name: '云也路亚营地', type: '路亚', typeEmoji: '🎮',
    city: '上海', district: '青浦', address: '青浦区东庆路8号',
    latitude: 31.09, longitude: 121.05,
    images: ['https://picsum.photos/seed/s035a/800/500', 'https://picsum.photos/seed/s035b/800/500'],
    fishSpecies: ["笋壳鱼", "鳜鱼", "鲈鱼", "翘嘴", "金目鲈", "虹鳟", "金鳟", "七彩鲑", "海鲈", "黑鱼", "太阳鱼", "珍珠斑"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-28',
    stockingCycleDays: 30,
    price: 168, priceNote: '￥168/天（7-24点），押金￥100；专享钓台￥198/天；露营天幕￥158/天；女士/1.4m以下儿童半价￥85', businessHours: '07:00-24:00（周五18:30-24:00）',
    contactPhone: '18916582901',
    wechat: null,
    ownerName: '云也路亚',
    rating: 4.6, reviewCount: 87, viewCount: 7800, favoriteCount: 934, postCount: 42,
    description: '上海青浦精品路亚塘，笋壳/鳜鱼/鲈鱼密度高。回鱼：鳜鱼￥20/斤、笋壳￥15/斤、翘嘴￥3/斤、超级猪笋￥10/斤。配套露营天幕+BBQ炉。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    hasAccommodation: true,
    roomType: '露营天幕/帐篷位',
    roomCapacity: null,
    hasWifi: false,
    accommodationNote: '露营天幕158元/顶（双人），可过夜。自带帐篷也可，营地有基础配套。',
    submitter: SpotSubmitter.owner,
    claimedBy: '云也路亚',
    claimedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Spot(
    id: 's053', name: '淀山湖', type: '野钓', typeEmoji: '🐟',
    city: '上海', district: '青浦', address: '沪青平公路7300号金舟渔村一带',
    latitude: 31.1, longitude: 120.95,
    images: ['https://picsum.photos/seed/s053a/800/500'],
    fishSpecies: ["翘嘴", "红尾", "白条", "鲫鱼"],
    fishPeakSeason: const { '翘嘴': '6-9', '红尾': '5-9', '白条': '5-9', '鲫鱼': '3-11' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '湖岸野钓免费，路亚标点常见', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.5, reviewCount: 92, viewCount: 1320, favoriteCount: 230, postCount: 14,
    description: '上海最大天然淡水湖，抖音钓友常驻路亚红尾翘嘴标点，夜钓人气高。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's054', name: '滴水湖', type: '野钓', typeEmoji: '🐟',
    city: '上海', district: '浦东新区', address: '临港新城主城区环湖西一路',
    latitude: 31.06, longitude: 121.93,
    images: ['https://picsum.photos/seed/s054a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "翘嘴", "白条"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '翘嘴': '6-9', '白条': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '环湖野钓免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 54, viewCount: 880, favoriteCount: 120, postCount: 8,
    description: '临港人工湖，环境好，适合新手休闲野钓，周末家庭出游。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's055', name: '澜山钓场', type: '黑坑', typeEmoji: '🏴‍☠️',
    city: '上海', district: '奉贤', address: '奉贤区城大路289号',
    latitude: 30.92, longitude: 121.47,
    images: ['https://picsum.photos/seed/s055a/800/500'],
    fishSpecies: ["草鱼", "青鱼", "黑鱼", "鲈鱼", "翘嘴", "鳜鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-25',
    stockingCycleDays: 7,
    price: 200, priceNote: '200元/天', businessHours: '07:00-19:00',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.1, reviewCount: 33, viewCount: 480, favoriteCount: 60, postCount: 5,
    description: '奉贤综合钓场，手杆塘+路亚塘，配套农家乐餐饮。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's056', name: '铁岗水库', type: '野钓', typeEmoji: '🐟',
    city: '深圳', district: '宝安', address: '宝安区铁岗水库大坝段(鲲鹏径支线)',
    latitude: 22.62, longitude: 113.86,
    images: ['https://picsum.photos/seed/s056a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "罗非"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '罗非': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '新开放徒步钓鱼区，免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.0, reviewCount: 38, viewCount: 720, favoriteCount: 95, postCount: 7,
    description: '深圳宝藏新开放打卡地，碧波山色，可徒步赏花兼钓鱼。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's057', name: '坪山龙江钓鱼场', type: '斤塘', typeEmoji: '🎣',
    city: '深圳', district: '坪山', address: '坪山区金田路141号',
    latitude: 22.69, longitude: 114.33,
    images: ['https://picsum.photos/seed/s057a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "青鱼", "罗非", "黑鱼", "鲶鱼", "鲈鱼", "翘嘴", "鳜鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-23',
    stockingCycleDays: 7,
    price: 160, priceNote: '160元/4小时', businessHours: '07:00-20:00',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 47, viewCount: 690, favoriteCount: 102, postCount: 9,
    description: '深圳综合黑坑路亚场，鱼种齐全，钓鱼之家热门推荐。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's058', name: '福田河', type: '野钓', typeEmoji: '🐟',
    city: '深圳', district: '福田', address: '福田区福田河沿岸(市中心段)',
    latitude: 22.53, longitude: 114.06,
    images: ['https://picsum.photos/seed/s058a/800/500'],
    fishSpecies: ["鲫鱼", "罗非", "白条"],
    fishPeakSeason: const { '鲫鱼': '3-11', '罗非': '5-10', '白条': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费城市河流钓点', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 3.8, reviewCount: 26, viewCount: 410, favoriteCount: 48, postCount: 4,
    description: '深圳市区免费野钓首选，休闲便利，鱼情一般但胜在方便。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's059', name: '大沙河', type: '野钓', typeEmoji: '🐟',
    city: '深圳', district: '南山', address: '南山区大沙河生态长廊',
    latitude: 22.54, longitude: 113.95,
    images: ['https://picsum.photos/seed/s059a/800/500'],
    fishSpecies: ["鲫鱼", "罗非", "白条", "鲤鱼"],
    fishPeakSeason: const { '鲫鱼': '3-11', '罗非': '5-10', '白条': '5-9', '鲤鱼': '4-11' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 3.9, reviewCount: 29, viewCount: 450, favoriteCount: 52, postCount: 5,
    description: '南山生态河流钓点，环境优美，适合周末轻休闲。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's060', name: '抚仙湖', type: '野钓', typeEmoji: '🐟',
    city: '玉溪', district: '澄江', address: '玉溪市澄江市抚仙湖沿湖(禄充/孤山一带)',
    latitude: 24.5, longitude: 102.88,
    images: ['https://picsum.photos/seed/s060a/800/500'],
    fishSpecies: ["抗浪鱼", "鲫鱼", "鲤鱼", "银鱼"],
    fishPeakSeason: const { '抗浪鱼': '3-11', '鲫鱼': '3-11', '鲤鱼': '4-11', '银鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '湖岸野钓免费，开湖季需注意禁渔期', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.6, reviewCount: 110, viewCount: 1680, favoriteCount: 320, postCount: 18,
    description: '中国最深淡水湖之一，特有抗浪鱼，水质极好，云南野钓圣地。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's061', name: '星云湖', type: '野钓', typeEmoji: '🐟',
    city: '玉溪', district: '江川', address: '玉溪市江川区星云湖沿湖',
    latitude: 24.28, longitude: 102.74,
    images: ['https://picsum.photos/seed/s061a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "大头鱼"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '大头鱼': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '湖岸免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.1, reviewCount: 58, viewCount: 770, favoriteCount: 110, postCount: 9,
    description: '与抚仙湖一山之隔，鱼种丰富，大头鱼(大头鲤)为地方特色。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's062', name: '武汉东湖', type: '野钓', typeEmoji: '🐟',
    city: '武汉', district: '武昌', address: '武汉市武昌区东湖沿湖(听涛/磨山段)',
    latitude: 30.56, longitude: 114.39,
    images: ['https://picsum.photos/seed/s062a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "鳊鱼", "翘嘴"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '鳊鱼': '4-10', '翘嘴': '6-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '部分区域免费，少数收费塘', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 103, viewCount: 1500, favoriteCount: 280, postCount: 20,
    description: '千湖之省代表钓点，武汉钓友最多的城市湖库，竞技氛围浓。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's063', name: '十堰丹江口水库', type: '野钓', typeEmoji: '🐟',
    city: '十堰', district: '丹江口', address: '十堰市丹江口市丹江口水库(亚洲天池)',
    latitude: 32.54, longitude: 111.42,
    images: ['https://picsum.photos/seed/s063a/800/500'],
    fishSpecies: ["青鱼", "草鱼", "鳊鱼", "翘嘴", "鸭嘴鱼"],
    fishPeakSeason: const { '青鱼': '5-10', '草鱼': '4-10', '鳊鱼': '4-10', '翘嘴': '6-9', '鸭嘴鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '库区野钓(注意禁渔期/保护区)', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.4, reviewCount: 89, viewCount: 1280, favoriteCount: 210, postCount: 14,
    description: '1022km²亚洲天池，南水北调水源，大鱼多，钓鱼人向往之地。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's064', name: '松原查干湖', type: '野钓', typeEmoji: '🐟',
    city: '松原', district: '前郭', address: '松原市前郭县查干湖沿湖',
    latitude: 45.14, longitude: 124.82,
    images: ['https://picsum.photos/seed/s064a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "鲶鱼", "翘嘴", "胖头鱼"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '鲶鱼': '5-9', '翘嘴': '6-9', '胖头鱼': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '春夏季野钓免费，冬捕季闻名', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 72, viewCount: 1050, favoriteCount: 190, postCount: 12,
    description: '冬捕闻名全国的5A湖区，夏季野钓也宜人，胖头鱼(鳙)为特色。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's065', name: '鄱阳湖', type: '野钓', typeEmoji: '🐟',
    city: '上饶', district: '鄱阳', address: '上饶市鄱阳县鄱阳湖沿湖(枯水季草洲钓点)',
    latitude: 29.0, longitude: 116.67,
    images: ['https://picsum.photos/seed/s065a/800/500'],
    fishSpecies: ["鲫鱼", "鲤鱼", "草鱼", "鳊鱼", "鲶鱼"],
    fishPeakSeason: const { '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '鳊鱼': '4-10', '鲶鱼': '5-9' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '湖岸野钓免费(注意水位/禁渔期)', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.1, reviewCount: 66, viewCount: 920, favoriteCount: 150, postCount: 10,
    description: '中国第一大淡水湖，江西钓鱼资源核心，枯水季草洲钓点独特。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),
    Spot(
    id: 's066', name: '鄂州梁子湖', type: '野钓', typeEmoji: '🐟',
    city: '鄂州', district: '梁子湖', address: '鄂州市梁子湖区梁子湖沿湖',
    latitude: 30.25, longitude: 114.58,
    images: ['https://picsum.photos/seed/s066a/800/500'],
    fishSpecies: ["武昌鱼", "鲫鱼", "鲤鱼", "草鱼", "鳊鱼"],
    fishPeakSeason: const { '武昌鱼': '4-10', '鲫鱼': '3-11', '鲤鱼': '4-11', '草鱼': '4-10', '鳊鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '湖岸野钓免费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.2, reviewCount: 58, viewCount: 800, favoriteCount: 130, postCount: 9,
    description: '武昌鱼(团头鲂)故乡，湖北代表性湖库，鱼鲜景美。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    ),

  // ---- 昆明延伸路亚钓点 ----
  Spot(
    id: 's067', name: '星路亚·盘龙区农场', type: '路亚', typeEmoji: '🎮',
    city: '昆明', district: '盘龙', address: '昆明市盘龙区滇源街道老坝村委会得食新村旁',
    latitude: 25.132, longitude: 102.824,
    images: ['https://picsum.photos/seed/s067a/800/500', 'https://picsum.photos/seed/s067b/800/500'],
    fishSpecies: ["鲈鱼", "鳜鱼", "翘嘴", "草鱼", "鲤鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-02',
    stockingCycleDays: 30,
    price: 0, priceNote: '免费野钓区域+餐饮收费',
    businessHours: '全天开放',
    contactPhone: null,
    wechat: null,
    ownerName: '星路亚农场（工商注册）',
    rating: 4.2, reviewCount: 34, viewCount: 2800, favoriteCount: 156, postCount: 9,
    description: '种养结合农场，含路亚练杆区与休闲垂钓区。露营、烧烤、采摘配套全，环境清幽适合家庭周末出行。鱼种丰富，鲈/鳜/翘嘴密度适中。',
    updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    submitter: SpotSubmitter.operator,
  ),
  Spot(
    id: 's068', name: '梦想路亚', type: '路亚', typeEmoji: '🎮',
    city: '昆明', district: '官渡', address: '昆明市官渡区昆磨高速杜家营水库北',
    latitude: 24.971, longitude: 102.774,
    images: ['https://picsum.photos/seed/s068a/800/500', 'https://picsum.photos/seed/s068b/800/500'],
    fishSpecies: ["鲈鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-01',
    stockingCycleDays: 30,
    price: 78, priceNote: '￥78/人/杆/天；会员1400元/20次；鲈鱼称斤65元/斤',
    businessHours: '全天（无半天收费）',
    contactPhone: null,
    wechat: null,
    ownerName: null,
    rating: 4.3, reviewCount: 89, viewCount: 5600, favoriteCount: 445, postCount: 27,
    description: '市区内路亚练杆塘，8亩水面，水深2-2.5米。鲈鱼密度高，适合新手练抛投。导航杜家营水库或搜"梦想路亚"。无半天收费，随到随钓，会员性价比高。',
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    submitter: SpotSubmitter.operator,
  ),

  // ── 贵州 ──────────────────────────────────────────────
  Spot(
    id: 's069', name: '新长征水库', type: '野钓', typeEmoji: '🐟',
    city: '黔东南', district: '丹寨县', address: '黔东南苗族侗族自治州丹寨县新长征水库',
    latitude: 26.202, longitude: 108.806,
    images: ['https://picsum.photos/seed/s069a/800/500'],
    fishSpecies: ["草鱼", "青鱼", "鲤鱼", "鳊鱼"],
    fishPeakSeason: const { '草鱼': '4-10', '青鱼': '5-10', '鲤鱼': '4-11', '鳊鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 100, priceNote: '100元/天', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: null,
    rating: 4.1, reviewCount: 34, viewCount: 1200, favoriteCount: 89, postCount: 5,
    description: '水库100亩，三口地下水涌出加山泉水汇流，水质好。鱼味鲜美，可垂钓可出售，休闲娱乐于一体的垂钓圣地，可亲自下厨体验。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's070', name: '罗妥岸钓基地', type: '斤塘', typeEmoji: '🚫',
    city: '黔南', district: '罗甸县', address: '黔南布依族苗族自治州罗甸县下儒村母亭组',
    latitude: 25.426, longitude: 106.748,
    images: ['https://picsum.photos/seed/s070a/800/500'],
    fishSpecies: ["罗非", "鲤鱼", "草鱼", "翘嘴"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-30',
    stockingCycleDays: 7,
    price: 230, priceNote: '230元/天', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: null,
    rating: 4.3, reviewCount: 56, viewCount: 2300, favoriteCount: 178, postCount: 9,
    description: '贵州罗甸高原千岛湖蒙江水域，大鱼多，罗非多。贵阳过来2小时，下高速2分钟到码头，无山路，交通便利。可路亚、筏钓、岸钓，环境优美，鱼资源丰富。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's071', name: '万峰湖-润龙湾水上世界', type: '游钓基地', typeEmoji: '🏀',
    city: '黔西南', district: '兴义市', address: '黔西南布依族苗族自治州兴义市万峰湖润龙湾',
    latitude: 25.091, longitude: 104.853,
    images: ['https://picsum.photos/seed/s071a/800/500'],
    fishSpecies: ["翘嘴", "罗非", "鳜鱼", "鲤鱼", "草鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-29',
    stockingCycleDays: 30,
    price: 180, priceNote: '160-200元/天（含岸钓加船钓）', businessHours: '06:00-20:00',
    contactPhone: null,
    wechat: null, ownerName: '润龙湾钓场',
    hasAccommodation: true,
    roomType: '湖畔客房',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '配套钓场客房，可容纳40-50人，有餐饮。',
    rating: 4.4, reviewCount: 189, viewCount: 6700, favoriteCount: 723, postCount: 38,
    description: '钓场面积约4800亩，岸钓水深约3-6米，筏钓水深约10-30米。润龙湾水上世界专业打造，可接纳40-50人。是黔西南万峰湖最成熟的游钓基地之一。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's072', name: '万峰湖-云水间民宿', type: '游钓基地', typeEmoji: '🏀',
    city: '黔西南', district: '兴义市', address: '黔西南布依族苗族自治州兴义市万峰湖下游梅家湾',
    latitude: 25.083, longitude: 104.840,
    images: ['https://picsum.photos/seed/s072a/800/500'],
    fishSpecies: ["翘嘴", "罗非", "鳜鱼", "鲤鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-28',
    stockingCycleDays: 30,
    price: 258, priceNote: '258元/天（含住宿）', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: '云水间民宿',
    hasAccommodation: true,
    roomType: '豪华湖景房',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '下高速25公里车直达水边，下车就钓鱼，无需坐船。',
    rating: 4.5, reviewCount: 203, viewCount: 8900, favoriteCount: 1100, postCount: 52,
    description: '万峰湖下游梅家湾，水面最宽最深处之一，湖景绝美。豪华湖景房，喜得钓友热爱，是看湖景加日出的好地方。距离市区高铁站飞机场40公里左右。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's073', name: '北斗湾国际路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '贵阳', district: '花溪区', address: '贵阳市花溪区北斗湾（高德导航北斗湾国际路亚基地）',
    latitude: 26.408, longitude: 106.657,
    images: ['https://picsum.photos/seed/s073a/800/500'],
    fishSpecies: ["鲈鱼", "鳜鱼", "翘嘴", "军鱼", "丁桂鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-27',
    stockingCycleDays: 30,
    price: 150, priceNote: '咨询基地定价', businessHours: '08:00-18:00',
    contactPhone: null,
    wechat: null, ownerName: '贵州野钓衢体育文化传媒',
    rating: 4.6, reviewCount: 145, viewCount: 7800, favoriteCount: 890, postCount: 41,
    description: '贵州野钓衢体育文化传媒有限公司旗下基地，位于贵州省会城市贵阳。国际路亚基地，结构丰富，管理规范。与长顺麦况水库国际路亚基地同属一家公司运营。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  // ── 云南 ──────────────────────────────────────────────
  Spot(
    id: 's074', name: '红河-元阳神仙湾农家乐', type: '农家乐', typeEmoji: '🏕',
    city: '红河', district: '元阳县', address: '云南省红河哈尼族彝族自治州元阳县小蛮提神仙湾',
    latitude: 23.218, longitude: 102.745,
    images: ['https://picsum.photos/seed/s074a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "罗非", "黄颡鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-26',
    stockingCycleDays: 30,
    price: 0, priceNote: '免费野钓，提供餐饮住宿', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: '神仙湾农家乐',
    hasAccommodation: true,
    roomType: '农家乐客房',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '清真农家乐，含食宿，联系电话：13769373511（王），建议提前预约。',
    rating: 4.2, reviewCount: 67, viewCount: 3400, favoriteCount: 234, postCount: 12,
    description: '红河州元阳哈尼梯田水系野钓渔庄，清真。梯田灌溉渠系水质好，鱼种丰富，环境优美。游客钓友皆可，是休闲娱乐好去处。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's075', name: '远大玉龙湾国际路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '昆明', district: '安宁市', address: '云南省昆明市安宁市太平镇玉龙湾（导航玉龙湾高尔夫球会停车场）',
    latitude: 24.923, longitude: 102.487,
    images: ['https://picsum.photos/seed/s075a/800/500'],
    fishSpecies: ["鲈鱼", "军鱼", "丁桂鱼", "鳜鱼", "翘嘴"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-25',
    stockingCycleDays: 30,
    price: 150, priceNote: '150元/天（含艇）', businessHours: '08:00-18:00',
    contactPhone: '0871-68630526',
    wechat: null, ownerName: '玉龙湾国际路亚基地',
    hasAccommodation: true,
    roomType: '基地会所/酒店',
    roomCapacity: 2,
    hasWifi: true,
    accommodationNote: '基地配备300平方俱乐部会所、餐饮、停车场。可预约有偿接机服务（长水机场至基地约1小时）。',
    rating: 4.7, reviewCount: 412, viewCount: 23000, favoriteCount: 4500, postCount: 156,
    description: '西南地区唯一专业路亚基地，水面作钓面积约500亩，两面环山，结构丰富复杂。配备20条专业路亚钓鱼艇、专业停泊码头、救援艇。目标鱼种：鲈鱼、军鱼、丁桂鱼等。承办过多届全国路亚大赛。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
    claimedBy: '远大玉龙湾国际路亚基地',
    claimedAt: DateTime.now().subtract(const Duration(days: 1)),
  ),

  Spot(
    id: 's076', name: '临沧-凤庆鲁史浴龙岛路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '临沧', district: '凤庆县', address: '云南省临沧市凤庆县鲁史镇永发村浴龙岛',
    latitude: 24.586, longitude: 99.914,
    images: ['https://picsum.photos/seed/s076a/800/500'],
    fishSpecies: ["鲈鱼", "鳜鱼", "翘嘴", "鲤鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-24',
    stockingCycleDays: 30,
    price: 0, priceNote: '比赛基地，费用请咨询赛事主办方', businessHours: '预约开放',
    contactPhone: null,
    wechat: null, ownerName: null,
    rating: 4.3, reviewCount: 89, viewCount: 5600, favoriteCount: 567, postCount: 23,
    description: '2024年云南省首届路亚锦标赛总决赛举办地，位于临沧市凤庆县鲁史镇永发村浴龙岛路亚基地。云南路亚运动标志性赛事场地，水域条件优越。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  // ── 四川 ──────────────────────────────────────────────
  Spot(
    id: 's077', name: '南充-升钟湖凤凰岛', type: '野钓', typeEmoji: '🐟',
    city: '南充', district: '南部县', address: '四川省南充市南部县升钟湖凤凰岛（导航：升钟湖山水印象休闲山庄）',
    latitude: 31.432, longitude: 105.864,
    images: ['https://picsum.photos/seed/s077a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鲢鳙", "鳊鱼", "翘嘴", "鳜鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '鲢鳙': '5-9', '鳊鱼': '4-10', '翘嘴': '6-9', '鳜鱼': '5-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 0, priceNote: '升钟湖湖面免费，部分农家乐收住宿费', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: null,
    hasAccommodation: true,
    roomType: '湖畔农家乐',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '升钟湖凤凰岛周边有多家农家乐提供住宿餐饮，含三餐约80-120元/天，请提前联系。',
    rating: 4.5, reviewCount: 234, viewCount: 12000, favoriteCount: 1800, postCount: 67,
    description: '升钟湖凤凰岛水域，湖区面积56平方公里，最深处170多米，被誉为中国钓鱼城。鱼类品种丰富：中国钓鱼节等多项国家级赛事举办地。是四川乃至全国最具影响力野钓圣地。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's078', name: '广元-升钟湖畔冯家湾小华钓鱼', type: '野钓', typeEmoji: '🐟',
    city: '广元', district: '剑阁县', address: '四川省广元市剑阁县涂山镇升钟湖畔冯家湾',
    latitude: 32.291, longitude: 105.575,
    images: ['https://picsum.photos/seed/s078a/800/500'],
    fishSpecies: ["红尾", "翘嘴", "高背鲫", "鲤鱼", "草鱼"],
    fishPeakSeason: const { '红尾': '5-9', '翘嘴': '6-9', '高背鲫': '3-11', '鲤鱼': '4-11', '草鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 90, priceNote: '90元/天（含住宿餐饮）', businessHours: '全天开放',
    contactPhone: null,
    wechat: null, ownerName: '冯家湾小华钓鱼',
    hasAccommodation: true,
    roomType: '湖畔客房（空调加独卫）',
    roomCapacity: 2,
    hasWifi: false,
    accommodationNote: '房间带空调、独立卫生间、热水，干净卫生。可接待手杆、机杆、路亚、海杆。',
    rating: 4.3, reviewCount: 78, viewCount: 3200, favoriteCount: 290, postCount: 18,
    description: '升钟湖畔冯家湾，青山绿水，环境优美，空气清新。水深3-20米，根据不同季节水位露出各钓位。可路亚、可手杆，交通便利，停车方便，住宿条件好（房间带空调独卫热水）。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's079', name: '成都-开心路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '成都', district: '锦江区', address: '四川省成都市三圣乡（高德导航：开心路亚基地）',
    latitude: 30.629, longitude: 104.136,
    images: ['https://picsum.photos/seed/s079a/800/500'],
    fishSpecies: ["鲈鱼", "鳜鱼", "翘嘴", "黑鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-07-21',
    stockingCycleDays: 30,
    price: 88, priceNote: '88元/8小时', businessHours: '07:00-19:00',
    contactPhone: '15928579079',
    wechat: '15928579079', ownerName: '开心路亚基地',
    rating: 4.4, reviewCount: 178, viewCount: 8900, favoriteCount: 980, postCount: 45,
    description: '成都近郊专业路亚基地，水域面积五亩，位于三圣乡附近，停车方便，环境优美。配备专业路亚艇和标点，是成都钓友日常练竿的好去处。电话微信同步。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's080', name: '成都-一月路亚基地', type: '路亚', typeEmoji: '🎮',
    city: '成都', district: '锦江区', address: '四川省成都市三圣乡（高德导航：一月路亚基地）',
    latitude: 30.631, longitude: 104.138,
    images: ['https://picsum.photos/seed/s080a/800/500'],
    fishSpecies: ["鲈鱼", "鳜鱼", "翘嘴", "黑鱼"],
    fishPeakSeason: const <String, String>{},
    lastStockingDate: '2026-08-09',
    stockingCycleDays: 30,
    price: 88, priceNote: '88元/8小时', businessHours: '07:00-19:00',
    contactPhone: '19950379608',
    wechat: '19950379608', ownerName: '一月路亚基地',
    rating: 4.5, reviewCount: 201, viewCount: 11200, favoriteCount: 1340, postCount: 58,
    description: '成都三圣乡专业路亚基地，水域面积10亩，结构丰富，可玩性高。高德导航直达，联系电话微信同步。成都本地钓友口碑佳，适合周末约钓。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  Spot(
    id: 's081', name: '成都-花龙水库垂钓中心', type: '野钓', typeEmoji: '🐟',
    city: '成都', district: '彭州市', address: '四川省成都市彭州市丽春镇长廊村4组（导航：花龙水库垂钓中心）',
    latitude: 30.954, longitude: 103.942,
    images: ['https://picsum.photos/seed/s081a/800/500'],
    fishSpecies: ["鲤鱼", "草鱼", "青鱼", "鲢鳙", "鳊鱼"],
    fishPeakSeason: const { '鲤鱼': '4-11', '草鱼': '4-10', '青鱼': '5-10', '鲢鳙': '5-9', '鳊鱼': '4-10' },
    lastStockingDate: null,
    stockingCycleDays: 0,
    price: 128, priceNote: '128元/8小时，鱼获自由，回鱼3元/斤', businessHours: '06:00-24:00',
    contactPhone: null,
    wechat: null, ownerName: null,
    rating: 4.2, reviewCount: 156, viewCount: 7800, favoriteCount: 654, postCount: 34,
    description: '2024年8月1日首次开塘，30亩大水库，底鱼万斤。一人一杆，限杆7.2米，鱼获自由，回鱼3元/斤。先交费后下杆。营业时间长，停车方便。是成都近郊新开的人气野钓大物塘。',
    updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    submitter: SpotSubmitter.operator,
  ),

  ];

  static List<Spot> get all => _mockSpots;

  static List<Spot> byCity(String city) =>
      _mockSpots.where((s) => s.city == city).toList();

  static List<Spot> byType(String type) =>
      _mockSpots.where((s) => s.type == type).toList();

  static List<Spot> search(String q) {
    final lq = q.toLowerCase();
    return _mockSpots.where((s) =>
      s.name.contains(lq) ||
      s.city.contains(lq) ||
      s.fishSpecies.any((f) => f.toLowerCase().contains(lq))
    ).toList();
  }

  static List<Spot> sortByHotspot([List<Spot>? spots]) {
    final src = spots ?? _mockSpots;
    final copy = List<Spot>.from(src);
    copy.sort((a, b) {
      final sa = a.hotspotScore;
      final sb = b.hotspotScore;
      return sb.compareTo(sa);
    });
    return copy;
  }

  static void addSpot(Spot spot) {
    _mockSpots.insert(0, spot);
  }

  static Spot? claimSpot(String id, {
    String? contactPhone, String? wechat, String? ownerName,
    String? lastStockingDate, int? stockingCycleDays,
  }) {
    final idx = _mockSpots.indexWhere((s) => s.id == id);
    if (idx < 0) return null;
    final old = _mockSpots[idx];
    final updated = Spot(
      id: old.id, name: old.name, type: old.type, typeEmoji: old.typeEmoji,
      city: old.city, district: old.district, address: old.address,
      latitude: old.latitude, longitude: old.longitude,
      images: old.images, fishSpecies: old.fishSpecies, fishPeakSeason: old.fishPeakSeason,
      lastStockingDate: lastStockingDate ?? old.lastStockingDate,
      stockingCycleDays: stockingCycleDays ?? old.stockingCycleDays,
      price: old.price, priceNote: old.priceNote,
      businessHours: old.businessHours,
      contactPhone: contactPhone ?? old.contactPhone,
      wechat: wechat ?? old.wechat,
      ownerName: ownerName ?? old.ownerName,
      rating: old.rating, reviewCount: old.reviewCount,
      viewCount: old.viewCount, favoriteCount: old.favoriteCount,
      postCount: old.postCount,
      description: old.description,
      updatedAt: DateTime.now(),
      submitter: SpotSubmitter.owner,
      claimedBy: ownerName,
      claimedAt: DateTime.now(),
    );
    _mockSpots[idx] = updated;
    return updated;
  }

  static Spot? getOne(String id) {
    try {
      return _mockSpots.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }

  /// 计算两点间距离（Haversine公式，单位km）
  static double distanceBetween(
    double lat1, double lon1,
    double lat2, double lon2,
  ) {
    const R = 6371.0; // 地球半径（km）
    final dLat = _toRad(lat2 - lat1);
    final dLon = _toRad(lon2 - lon1);
    final a = 0.5 - 0.5 * cos(2 * dLat) +
             0.5 * cos(2 * dLon) * cos(_toRad(lat1)) * cos(_toRad(lat2));
    return R * 2 * asin(sqrt(a));
  }

  static double _toRad(double deg) => deg * 0.01745329252;

  /// 按距离排序（需用户坐标）
  static List<Spot> sortByDistance(
    List<Spot> spots,
    double userLat,
    double userLon,
  ) {
    final copy = List<Spot>.from(spots);
    copy.sort((a, b) {
      final da = distanceBetween(userLat, userLon, a.latitude, a.longitude);
      final db = distanceBetween(userLat, userLon, b.latitude, b.longitude);
      return da.compareTo(db);
    });
    return copy;
  }
}
